name = "hockey-stats-mcp"
main = "src/index.js"
compatibility_date = "2025-01-06"

# Self-contained - Direct NHL API integration

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }