name = "hockey-resolver-mcp"
main = "src/index.js"
compatibility_date = "2024-12-18"

[env.production]
name = "hockey-resolver-mcp"

[[d1_databases]]
binding = "HOCKEY_DB"
database_name = "hockey_resolver_db"
database_id = "hockey-resolver-db-dev"

[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"