name = "hockey-fantasy-mcp"
main = "src/index.js"
compatibility_date = "2025-01-06"

# Durable Objects for user session storage
[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserSession"]

[env.production]
vars = { ENVIRONMENT = "production" }
# Yahoo OAuth credentials - set these as secrets in production
# wrangler secret put YAHOO_CLIENT_ID
# wrangler secret put YAHOO_CLIENT_SECRET

[env.development]
vars = { ENVIRONMENT = "development" }
# For development, add your Yahoo OAuth credentials here:
# YAHOO_CLIENT_ID = "your_yahoo_client_id"
# YAHOO_CLIENT_SECRET = "your_yahoo_client_secret"